### ISSUE TITLE
License mismatch between package.json and readme.txt

### ISSUE THREAD

**Issue by allendoerfer** [caseproof/members#101]
Hi there,

I think the license field in package.json should be updated to also say GPLv2.

Regards and thanks for the great work!

**Comment by DumahX** [comment]
Hi @allendoerfer,

Thank you for reaching out and bringing this to our attention. This has been addressed in the [following commit](https://github.com/caseproof/members/commit/bb702d80ee61cf4a1765dba8c056a8ed0fcb2f66) and will be made available in the next release of Members.
