### ISSUE TITLE
Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by DSGND** [caseproof/members#116]
https://github.com/caseproof/members/blob/1bf477fff500e305cecebfd93d54b591aaa56ad0/addons/members-acf-integration/src/Plugin.php#L246C1-L247C1

PHP Deprecated:  Automatic conversion of false to array is deprecated in /plugins/members/addons/members-acf-integration/src/Plugin.php on line 246

This is a notice in PHP 8.1. It can be fixed by merging the array:

```
$args['supports'] = array_merge((array)$args['supports'], array('author'));
```

**Comment by cartpauj** [comment]
Fixed in: https://github.com/caseproof/members/pull/117
Thanks for the report.
