### ISSUE TITLE
Manage Memberpress Access with Members plugin

### ISSUE THREAD

**Issue by Elaniobro** [caseproof/members#118]
I am looking to create a new role: `Membership Team` that will allow users with the role to manage `Member press` users.

The only option/capabilities I see within `Members` is for `Users`.

What I _need_ is the ability to expose the `member press dashboard` and grant read/write access to various part of it. How would one do so?

**Comment by Elaniobro** [comment]
@cartpauj, was there an update pushed out that closes this issue?

**Comment by cartpauj** [comment]
No, MemberPress doesn't currently support fine-grained controls so this is not possible at the moment.

Will revisit if/when we're able to get fine-grained capability/role checks in MemberPress.
