### ISSUE TITLE
Revert plugin title to Members

### ISSUE THREAD

**Issue by johnbillion** [caseproof/members#12]
I've been a big fan of Members for many years, and I appreciate the recent changes including rolling the add-ons into the free version of the plugin.

That said, the new plugin title reflects very poorly on this otherwise good quality plugin. It is spammy, its only purpose is for SEO, it cheapens the plugin, it's frankly embarrassing, and it makes me hesitate to any longer recommend the plugin to anyone because of its spammy title.

Imagine if every plugin had such spam in its title. What a nightmare.

Please, revert the title back to "Members" and add some class back to the plugin. Do your SEO elsewhere.

**Comment by ocean90** [comment]
The [plugin title is still Members](https://github.com/caseproof/members/blob/d17484b3555adfd79d35f061434c153956240eac/members.php#L3), it's only about the [page title in the directory](https://wordpress.org/plugins/members/).

Having a few extra keywords in the title isn't bad but I guess it can be simplified to "Members – Membership and User Role Management".

**Comment by ocean90** [comment]
The page title was updated in https://github.com/caseproof/members/commit/ba30ffd721081319c6f220c100db8708608e7b25. Thank you @supercleanse!
