### ISSUE TITLE
relation to WP Members Membership plugin?

### ISSUE THREAD

**Issue by RRcwhiting** [caseproof/members#123]
Is this the upstream for WP Members?

https://www.securityweek.com/security-flaw-in-wp-members-plugin-leads-to-script-injection/

https://www.wordfence.com/blog/2024/04/unauthenticated-stored-cross-site-scripting-vulnerability-patched-in-wp-members-membership-plugin-500-bounty-awarded/

Are there any plans to patch the free version, too?

**Comment by KristaButler** [comment]
Members is not the free version of WP Members Memberships, it's a complete seperate plugin built by a different team. You will have to contact the [WP Members Membership](https://wordpress.org/plugins/wp-members/) team for information about the patch.

**Comment by RRcwhiting** [comment]
Neat, so you're not affected by it? :)
