### ISSUE TITLE
Fix translation notice in WP 6.7

### ISSUE THREAD

**Issue by ThemeGravity** [caseproof/members#126]
After upgrading to WP 6.7 there is a notice related to translation loading too early. We had similar issue in MP:

_Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the members domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /www/securedev1_768/public/wp-includes/functions.php on line 6114_

**Comment by cartpauj** [comment]
@ThemeGravity I think you just need to change the hook where the language is loaded to `after_setup_theme`

**Comment by cartpauj** [comment]
https://github.com/caseproof/members/blob/0b92bfea5db6ba3042cc1d3c44784b77c7387bad/members.php#L272

**Comment by cartpauj** [comment]
And also one of the add-ons seems to have it also:
https://github.com/caseproof/members/blob/0b92bfea5db6ba3042cc1d3c44784b77c7387bad/addons/members-acf-integration/src/Plugin.php#L50
