### ISSUE TITLE
Fix Members About Us page

### ISSUE THREAD

**Issue by cartpauj** [caseproof/members#133]
- [x] Tiles are broken (formatting)
- [x] About Us link in footer is broken

Screenshot: https://cdn.zappy.app/2e49c62b6629def6ef99155e2fea3026.png

**Comment by cartpauj** [comment]
Fixed about us page in https://github.com/caseproof/members/commit/8a42dbd6efb1dd3dce4c3e4f80f1064c7cb8bcf4

**Comment by ThemeGravity** [comment]
@cartpauj Here is a video (no audio) where you can see page's responsiveness: 


https://github.com/user-attachments/assets/9d50cc19-e51a-4192-abff-076ba6184170

**Comment by cartpauj** [comment]
Thanks @ThemeGravity 

Let's set a min-width on the tiles so they're all the same size: https://prnt.sc/DU4kw3cbDJmI

And I think we can move to the rows at a higher resolution so the 3 rows don't get squished so tightly.

**Comment by ThemeGravity** [comment]
@cartpauj I fixed the width and changed column layout starting from 1100px here: https://github.com/caseproof/members/pull/143/commits/60b66a24e020e6b1068652a3a2835528b4a24eb7. 
I couldn't make it smaller because the sidebar shows up when the screen width is 960px.
