### ISSUE TITLE
Security issue/feature request: allowing users to add roles they do not have access to themselves

### ISSUE THREAD

**Issue by hphoeksma** [caseproof/members#18]
I created a role to enable one of the users to be able to create editors for their company website.
So this role adds the possibility to create users and add roles to them.
To my surprise the user with this role has the option to allow promoting themselves to administrator - or any other role - and also is capable of creating users adding all available roles in the system.
I could not find any documentation on this, but this seems to be a security problem ;-)

**Comment by renventura** [comment]
@hphoeksma Hi there. So that I can test this out on my end, can you let me know all of the capabilities you've granted that role?

**Comment by hphoeksma** [comment]
@renventura of course,  and I might just made a wrong assumption looking again at the list of options. I marked 'promote users' as in interpreting this to mean 'the ability to assign roles'. Which is true, and needed. When unchecking this privilege the user with the role cannot assign roles and created users are getting the default role.

Summarizing it might not be a security issue but a feature request.

![image](https://user-images.githubusercontent.com/250683/84640019-6bfc2d80-aef9-11ea-91de-0b20ad292b1e.png)

**Comment by renventura** [comment]
This can be done as of Members `3.0.10`.
