### ISSUE TITLE
Posts titles are still visible even when the user does not have permission to view the post

### ISSUE THREAD

**Issue by dastra** [caseproof/members#2]
Currently, Post/Page titles are still visible in search results and if the user visits the page directly.  My preference would be that the user should not know that the post or page even exists if they do not have permission to view it.  

If this fits with your vision for the plugin, then I have a pull request ready which will implement this.  If not, fair enough!  Either way an excellent plugin - easily the best of the capabilities plugins :-)

**Comment by renventura** [comment]
Hi, @dastra. Feel free to submit your PR - we'd be happy to review and consider it. 😀

**Comment by cartpauj** [comment]
This could have unintended consequences for other users, we'll need to consider adding this as an opt-in feature instead.
