### ISSUE TITLE
SVG Error

### ISSUE THREAD

**Issue by hirenshah** [caseproof/members#3]
Your latest version results in the following when loading SVGs on the addons page:
`PHP Parse error:  syntax error, unexpected 'version' (T_STRING)`

It is an issue in the file:
`class-view-addons.php`

Change:
`<?php include members_plugin()->dir . "img/{$addon->name}.svg"; ?>`

To:
`<?php echo file_get_contents(members_plugin()->dir . "img/{$addon->name}.svg"); ?>`

**Comment by hirenshah** [comment]
@renventura 

The SVG was being treated as a PHP file, so rather than change the file you are loading, you should correct how you are actually loading it :)

**Comment by renventura** [comment]
@hirenshah Thanks for the commit! I actually pushed the minified changes before I saw this come in. In the meantime, the minified SVGs will prevent the error that was being thrown. We'll definitely re-evaluate how the SVGs are being loaded, though - I like your suggestion. We appreciate the time you took to report and commit. 😀

**Comment by renventura** [comment]
Fixed in 8e602e0129ea6346bc5eeaadf45a671d07dc5fa0
