### ISSUE TITLE
Gutenberg options shows svg-code

### ISSUE THREAD

**Issue by pixolin** [caseproof/members#31]
To display the _Members_ meta box "content permissions" in the block editor I open the kebab menu (⋮) and go to options. The list of available options shows a block of svg-code instead of the option, only:

<a href="https://i.imgur.com/3ld3ibP.gif"><img src="https://i.imgur.com/3ld3ibP.gif" alt="screenshot block editor options"  width="80%"></a>

Tested on a local webserver with a plain vanilla WordPress 5.5.1 installation, default theme, no other plugins activated.

**Comment by bdfire** [comment]
https://github.com/caseproof/members/blob/637171d49425adf23435beeb06b4a81151818549/admin/class-meta-box-content-permissions.php#L115

This is the line of code causing the issue.
