### ISSUE TITLE
Members Limitations

### ISSUE THREAD

**Issue by brunokrebs** [caseproof/members#34]
Sorry, couldn't find a single place that talks about this. So, what are the limitations on the free version? Will I face a limitation around the number of users, roles, or restricted pages?

**Comment by cartpauj** [comment]
Well MemberPress and Members are really two different plugins. They can even be used together...though that's not really necessary.

**Members** is focused on allowing an Admin to have much finer control over the WP Roles and Capabilities on the site. It also contains some very basic content protection and login features.

**MemberPress** on the other hand, is a full-featured Membership platform allowing site owners greater flexibly over their content protection. Offering different membership levels, and controlling which content members of each level can access. It has integrations with Stripe and PayPal for payment handling (one-time and recurring), and many, many other integrations like MailChimp, BuddyPress, bbPress, etc. It has full member self-management, email reminders for upcoming renewals or credit card expirations.
