### ISSUE TITLE
Changelog not updated for 3.1.4

### ISSUE THREAD

**Issue by Hastibe** [caseproof/members#38]
I posted ([here](https://wordpress.org/support/topic/changelog-for-3-1-4/)) on the plugin's WordPress support forum last week, asking if the 3.1.4 changelog ([it still only goes up to 3.1.3](https://github.com/caseproof/members/blob/master/changelog.md)) could be shared, but haven't heard back from anyone. Could someone please share the changelog, so that we know what was changed or added or removed, etc.?

**Comment by grappler** [comment]
Seems like it has been fixed here: https://github.com/caseproof/members/commit/f1c54fb54e5ed452b5d8f00971101ff1d41e61cc

**Comment by Hastibe** [comment]
@grappler -- thanks, back, because it has been a couple weeks and the 3.2.2 changelog still hasn't been listed.
