### ISSUE TITLE
Annoying Message to Rate it!!!

### ISSUE THREAD

**Issue by Christian-CFP** [caseproof/members#42]
Your message that appears constantly!!! on WP to rate the plugin is more than annoying!

Please don't!!!!!!!!!

**Comment by cartpauj** [comment]
You can remove it by clicking any of the following links:
Okay, you deserve it
I already did
Give Feedback

You can see the full code here: https://github.com/caseproof/members/blob/develop/admin/class-review-prompt.php

If you click those and it doesn't go away, you might have object or database caching that needs to be flushed.

**Comment by Christian-CFP** [comment]
No Sorry. I did that several times.
