### ISSUE TITLE
Documentation and Support Forum links in Help tab link to incorrect pages

### ISSUE THREAD

**Issue by nick-elpedes** [caseproof/members#78]
The documentation link in the plugin settings page links to an archived repository - [Link](https://github.com/justintadlock/members/blob/master/readme.md)

The Support Forum link in the plugin settings page links to an unsecure web page called Theme Hybrid - [Link (Click at your own risk; This is here just to show what the link (on the plugin page) links to)](https://themehybrid.com/board/topics)

**Comment by nick-elpedes** [comment]
Code in question: https://github.com/caseproof/members/blob/6af20929fa5dc0a39a3d89e0f2c048f1660d3289/admin/functions-help.php#L23-L24

**Comment by cartpauj** [comment]
Resolved in: https://github.com/caseproof/members/commit/e9dfeb23b7b58349ec2b37a5798f451ce36c4c34
