### ISSUE TITLE
Warning messages on opening Edit Page

### ISSUE THREAD

**Issue by Peter0312** [caseproof/members#8]
When I hit the Edit Page link from the black WP toolbar at the top of a page I get a series of warning messages flashed onto the screen and then get the normal editing page which seems to function properly.  The messages are not up long enough to do a copy, but I have two screenshots, one using the WP administrator account and one a new site editor role with page edit caps, set up with Members.

[Administrator](http://www.wcanag.org/images/screenshot1.png)
[Site Editor](http://www.wcanag.org/images/screenshot2.png)

I am running a new install of Members on the current version of Wordpress using the Munk theme.  I get the errors both on Firefox and when using an iPad

Active plugins:

- a3 Lazy Load
- Alfred, the Assistant
- Antispam Bee
- Broken Link Checker
- Easy Table of Contents
- Hide/Remove Metadata
- Kirki Customizer Framework
- Limit Login Attempts Reloaded
- Members
- Recent Posts Widget Extended
- Statify
- The Events Calendar
- TinyMCE Advanced
- WPForms Lite

I am new to Github, so apologies if I am doing this wrong.

**Comment by renventura** [comment]
Hi, @Peter0312. Can you let me know what the messages say?

**Comment by Peter0312** [comment]
I have typed in the text of the screenshots as per the text below (E&OE):

**Screenshot1**

Warning: in_array() expects parameter 2 to be array, bool given in /homepages/44/d702579473/htdocs/clickandbuilds/WestChiltingtonandNutbourneActionGroup/wp-content/plugins/members/members.php on line 446

Warning: Cannot modify header information - headers already sent by (output started at /homepages/44/d702579473/htdocs/clickandbuilds/WestChiltingtonandNutbourneActionGroup/wp-content/plugins/members/members.php:446 in /homepages/44//d702579473/htdocs/clickandbuilds/WestChiltingtonandNutbourneActionGroup/wp-admin/admin-header.php on line 9

The second screenshot was the same but with two additional lines which  were identical to line 2 above except that they ended:

... Group/wp-includes/option.php on line 961

... Group/wp-includes/option.php on line 962

Thank you for your prompt reply - much appreciated.

**Comment by renventura** [comment]
Thanks, @Peter0312! This will be fixed in our next update, which I expect to be released within the next day or two. It was fixed in 8e602e0129ea6346bc5eeaadf45a671d07dc5fa0.

**Comment by Peter0312** [comment]
My pleasure. Thank you for addressing it so promptly.

**Comment by renventura** [comment]
Members 3.0.3 has been released with a fix for this.
